export const data = {
    products: [
        {
            id: '1',
            name: 'Wazowski Meme Sticker',
            image: 'https://i.imgur.com/6rYzHLM.png',
            price: 2999,
            size: 'L',
            categories: 'Meme',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Brighten your day with the Wazowski Meme Sticker. This sticker features the iconic meme character, perfect for adding a touch of humor to your belongings.'
        },
        {
            id: '2',
            name: 'Chainsaw Man Sticker',
            image: 'https://i.imgur.com/f3FG73M.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Show your love for Chainsaw Man with this Anime sticker. A must-have for fans, it adds a cool vibe to your collection.'
        },
        {
            id: '3',
            name: 'Arctic Monkeys Sticker',
            image: 'https://i.imgur.com/lpzOjqs.png',
            price: 3500,
            size: 'L',
            categories: 'Music',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Celebrate your favorite band with the Arctic Monkeys Sticker. Perfect for music lovers, this sticker will make your items stand out.'
        },
        {
            id: '4',
            name: 'Spongebob Cockroach Sticker',
            image: 'https://i.imgur.com/buo3jkw.png',
            price: 2999,
            size: 'L',
            categories: 'Meme',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Bring a laugh with the Spongebob Cockroach Sticker. This meme sticker is great for fans of the show and those who love quirky humor.'
        },
        {
            id: '5',
            name: 'Happy Banana Cat Sticker',
            image: 'https://i.imgur.com/9gTne14.png',
            price: 2999,
            size: 'L',
            categories: 'Meme',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Add some cuteness to your collection with the Happy Banana Cat Sticker. This adorable meme sticker is sure to cheer you up.'
        },
        {
            id: '6',
            name: 'Haikyuu Nekoma Badge Sticker',
            image: 'https://i.imgur.com/VzU7noH.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Support your favorite volleyball team with the Haikyuu Nekoma Badge Sticker. Perfect for fans of the Anime series.'
        },
        {
            id: '7',
            name: 'Haikyuu Karasuno Badge Sticker',
            image: 'https://i.imgur.com/8pQ7DqM.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Show your love for Karasuno with this Haikyuu Badge Sticker. A great addition for any Haikyuu fan.'
        },
        {
            id: '8',
            name: 'Haikyuu Kageyama Sticker',
            image: 'https://i.imgur.com/DF82uku.png',
            price: 3500,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Celebrate your favorite setter with the Haikyuu Kageyama Sticker. Ideal for adding a touch of Anime flair to your items.'
        },
        {
            id: '9',
            name: 'Haikyuu Tsukki Sticker',
            image: 'https://i.imgur.com/43isebE.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Display your fandom with the Haikyuu Tsukki Sticker. Perfect for fans of the tall and stoic blocker.'
        },
        {
            id: '10',
            name: 'Haikyuu Chibi Tsukki Sticker',
            image: 'https://i.imgur.com/cRSDQoD.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Enjoy the cuteness of Haikyuu with the Chibi Tsukki Sticker. A delightful sticker for any fan of the series.'
        },
        {
            id: '11',
            name: 'Spy X Family Anya Sticker',
            image: 'https://i.imgur.com/mnUa4ru.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Bring the charm of Anya to your collection with the Spy X Family Sticker. A great pick for fans of the hit Anime series.'
        },
        {
            id: '12',
            name: 'Komi-san wa, Komyushou desu Sticker',
            image: 'https://i.imgur.com/fysFIBY.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Add Komi-san to your sticker collection with this cute and charming sticker. Perfect for fans of the series.'
        },
        {
            id: '13',
            name: 'Komi-san Panic Sticker',
            image: 'https://i.imgur.com/C2t4aIL.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Capture the hilarious moments of Komi-san with the Panic Sticker. A funny addition to any sticker collection.'
        },
        {
            id: '14',
            name: 'Komi-san Sticker',
            image: 'https://i.imgur.com/DI1dGzC.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Enjoy the shy charm of Komi-san with this delightful sticker. Perfect for fans of the series who appreciate a good meme.'
        },
        {
            id: '15',
            name: 'Hunter x Hunter Shizuku Sticker',
            image: 'https://i.imgur.com/ECfSyrp.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Show your appreciation for Shizuku from Hunter x Hunter with this stylish sticker. Ideal for Anime fans looking to personalize their belongings.'
        },
        {
            id: '16',
            name: 'Chainsaw Man Kobeni Sticker',
            image: 'https://i.imgur.com/rNCcpcr.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Express your love for Chainsaw Man with this Kobeni sticker. A great choice for fans who want to add some Anime flair to their collection.'
        },
        {
            id: '17',
            name: "Kiki's Delivery Service Jiji Sticker",
            image: 'https://i.imgur.com/xi4PX7I.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: "Bring a touch of magic to your belongings with this Jiji sticker from Kiki's Delivery Service. Perfect for fans of Studio Ghibli and its charming characters."
        },
        {
            id: '18',
            name: 'Spirited Away Kaonashi Sticker',
            image: 'https://i.imgur.com/KeY510S.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Show your appreciation for the mysterious No-Face from Spirited Away with this striking sticker. Ideal for Studio Ghibli enthusiasts.'
        },
        {
            id: '19',
            name: 'Choso Jujutsu Kaisen Sticker',
            image: 'https://i.imgur.com/vMpl4ei.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Celebrate your favorite character from Jujutsu Kaisen with this Choso sticker. A must-have for fans of the popular Anime series.'
        },
        {
            id: '20',
            name: 'Yuji Itadori Jujutsu Kaisen Sticker',
            image: 'https://i.imgur.com/jnLXDIZ.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Add a heroic touch to your collection with this Yuji Itadori sticker from Jujutsu Kaisen. Perfect for Anime fans looking to personalize their items.'
        },
        {
            id: '21',
            name: 'Makima Chainsaw Man Meme Sticker',
            image: 'https://i.imgur.com/FW286rG.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Show your appreciation for Makima from Chainsaw Man with this stylish meme sticker. Ideal for Anime fans who love a good laugh.'
        },
        {
            id: '22',
            name: 'Shinji Hopeless Evangelion Meme Sticker',
            image: 'https://i.imgur.com/KcbVlRx.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Express your inner struggles with this Shinji meme sticker from Evangelion. A great addition to any Anime fan\'s collection.'
        },
        {
            id: '23',
            name: 'My Neighbor Totoro Sticker',
            image: 'https://i.imgur.com/lLxL7xP.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Bring the magic of Studio Ghibli to your collection with this adorable Totoro sticker. Perfect for fans of My Neighbor Totoro.'
        },
        {
            id: '24',
            name: 'My Neighbor Totoro Sticker',
            image: 'https://i.imgur.com/a9jZZnZ.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Celebrate the whimsical world of My Neighbor Totoro with this charming sticker. Ideal for Studio Ghibli enthusiasts.'
        },
        {
            id: '25',
            name: 'Sawako Kimi ni Todoke Sticker',
            image: 'https://i.imgur.com/WwBb21f.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Capture the essence of Sawako from Kimi ni Todoke with this beautiful sticker. A great addition for fans of the heartwarming Anime.'
        },
        {
            id: '26',
            name: 'Kimi ni Todoke Sticker',
            image: 'https://i.imgur.com/Mo9J2hZ.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Express your love for Kimi ni Todoke with this delightful sticker. Perfect for fans of the touching series.'
        },
        {
            id: '28',
            name: 'Kageyama Chibi Haikyuu Sticker',
            image: 'https://i.imgur.com/cpUIrAE.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Show off your passion for Haikyuu with this cute Kageyama chibi sticker. A must-have for volleyball Anime fans.'
        },
        {
            id: '29',
            name: 'Shoyo Haikyu Chibi Sticker',
            image: 'https://i.imgur.com/Hs5iMpm.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Brighten up your belongings with this adorable Shoyo chibi sticker from Haikyuu. Perfect for fans of the energetic protagonist.'
        },
        {
            id: '30',
            name: 'Oikawa Haikyu Chibi Sticker',
            image: 'https://i.imgur.com/monGenY.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Add some flair to your collection with this Oikawa chibi sticker from Haikyuu. Ideal for fans of the charismatic setter.'
        },
        {
            id: '31',
            name: 'Kenma Haikyu Chibi Sticker',
            image: 'https://i.imgur.com/DQoIklV.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Celebrate your favorite character from Haikyuu with this Kenma chibi sticker. A great addition for fans of the analytical player.'
        },
        {
            id: '32',
            name: 'Hunter x Hunter Shizuku Sticker',
            image: 'https://i.imgur.com/dmP45aS.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Show your appreciation for Shizuku from Hunter x Hunter with this stylish sticker. Ideal for Anime fans looking to personalize their belongings.'
        },
        {
            id: '33',
            name: 'Kageyama Haikyu Bubble Sticker',
            image: 'https://i.imgur.com/lEaiJNo.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Add a touch of Haikyuu magic to your collection with this Kageyama bubble sticker. Perfect for fans of the volleyball series.'
        },
        {
            id: '34',
            name: "Kiki's Coffee Ghibli Sticker",
            image: 'https://i.imgur.com/ZaQzg1E.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Enjoy a cup of charm with this Kiki\'s Coffee sticker from Studio Ghibli. A delightful addition for fans of Kiki\'s Delivery Service.'
        },
        {
            id: '35',
            name: "Jiji Kiki's Delivery Service Ghibli Sticker",
            image: 'https://i.imgur.com/4hOdxLW.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Bring some feline magic to your collection with this Jiji sticker from Kiki\'s Delivery Service. Perfect for Studio Ghibli lovers.'
        },
        {
            id: '36',
            name: 'Tsukishima Arara Gomen Haikyu Meme Sticker',
            image: 'https://i.imgur.com/YIFUffl.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Show your love for Haikyuu with this hilarious Tsukishima meme sticker. A must-have for fans of the sharp-tongued middle blocker.'
        },
        {
            id: '37',
            name: 'Ocean Waves Ghibli Sticker',
            image: 'https://i.imgur.com/YroM8Ub.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Capture the essence of Studio Ghibli\'s Ocean Waves with this elegant sticker. Perfect for fans of this lesser-known gem.'
        },
        {
            id: '38',
            name: 'Jiro Horikoshi Ghibli Sticker',
            image: 'https://i.imgur.com/xgNct3G.png',
            price: 2999,
            size: 'L',
            categories: 'Anime',
            type: 'Sticker',
            countInStock: 1,
            rate: 5,
            numReviews: 10,
            description: 'Honor the brilliant mind behind The Wind Rises with this Jiro Horikoshi sticker. A great addition for fans of Studio Ghibli\'s poignant film.'
        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    ]
}
